dist: trusty
sudo: required
language: cpp
services:
  - docker

env:
  global:
    - MKL_DNN_REV: v0.16
    - MKL_DNN_INSTALL_SUFFIX: -0.16

cache:
  directories:
    - $HOME/downloads
    - $HOME/mkl-dnn${MKL_DNN_INSTALL_SUFFIX}

matrix:
  include:
    - os: linux
      env: PLATFORM_ID=linux-x86_64 BUILDENV_REPO=okapies/buildenv BUILDENV_TAG=linux-x64-gcc-5.5

# skip the installation step
install: true

before_script:
  - export PLATFORM_DIR=${TRAVIS_BUILD_DIR}/.travis/${PLATFORM_ID}
  - docker pull ${BUILDENV_REPO}:${BUILDENV_TAG} || true
  # Run a docker container and map Travis's $HOME to the container's $HOME
  # $HOME:$HOME = /home/travis                     : /home/travis
  #               /home/travis/build               : /home/travis/build
  #               /home/travis/build/<user>/<repo> : /home/travis/build/<user>/<repo>
  - export DOCKER_CONTAINER_ID=$(docker run --privileged -d -v $HOME:$HOME -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${BUILDENV_REPO}:${BUILDENV_TAG} /sbin/init)

script:
  - |
    echo "travis_fold:start:Run build.sh for ${PLATFORM_ID}"
    if [ -e "${PLATFORM_DIR}/build.sh" ]; then
      echo -e "\e[33;1mRunning .travis/${PLATFORM_ID}/build.sh on ${TRAVIS_REPO_SLUG}\e[0m"
      /bin/bash -ex ${PLATFORM_DIR}/build.sh ${DOCKER_CONTAINER_ID}
    fi
    echo "travis_fold:end:Run build.sh for ${PLATFORM_ID}"
  - cat ${HOME}/build/result.txt

after_script:
  # Stop the docker container
  - docker stop ${DOCKER_CONTAINER_ID}
  - docker rm -v ${DOCKER_CONTAINER_ID}
