dist: trusty
sudo: required
language: cpp
services:
  - docker

env:
  global:
    - PROTOBUF_VERSION: 3.6.1
    - MKLDNN_VERSION: 0.16

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/build/downloads
    - ${TRAVIS_BUILD_DIR}/build/protobuf-${PROTOBUF_VERSION}
    - ${TRAVIS_BUILD_DIR}/build/mkl-dnn-${MKLDNN_VERSION}

matrix:
  include:
    - os: linux
      env: PLATFORM_ID=linux-x86_64 BUILDENV_IMAGE=centos:centos7 GCC_VERSION=5.5.0

# skip the installation step
install: true

script:
  - bash -ex ${TRAVIS_BUILD_DIR}/.travis/run-build.sh
  - cat ${HOME}/build/result.txt
