dist: trusty
sudo: required
language: cpp
services:
  - docker

env:
  global:
    - PROTOBUF_VERSION: 3.6.1
    - MKLDNN_VERSION: 0.16

cache:
  directories:
    - $HOME/downloads
    - $HOME/protobuf-${PROTOBUF_VERSION}
    - $HOME/mkl-dnn-${MKLDNN_VERSION}

matrix:
  include:
    - os: linux
      env: PLATFORM_ID=linux-x86_64 BUILDENV_IMAGE=okapies/buildenv:linux-x64-gcc-7.3 GCC_VERSION=7.3.0

# skip the installation step
install: true

script:
  - bash -ex ${TRAVIS_BUILD_DIR}/.travis/run-build.sh
  - cat ${HOME}/build/result.txt
