dist: trusty
sudo: required
language: cpp
services:
  - docker

env:
  global:
    - PROTOBUF_VERSION: 3.6.1
    - MKLDNN_VERSION: 0.16
    - MAKE_JOBS: -j2

cache:
  directories:
    - ${HOME}/downloads
    - ${HOME}/build/protobuf-${PROTOBUF_VERSION}
    - ${HOME}/build/mkl-dnn-${MKLDNN_VERSION}

matrix:
  include:
    - os: linux
      env: PLATFORM=linux-x86_64 BUILDENV_IMAGE=okapies/buildenv:linux-x64-devtoolset-6

# skip the installation step
install: true

script:
  - bash -ex ${TRAVIS_BUILD_DIR}/.travis/run-build.sh
